groups:
  - name: NodeOperator
    rules:
      - alert: ClientSyncStatusBeacon
        expr: rocketpool_node_sync_progress{client="beacon"} < 1.0
        labels:
          severity: critical
        annotations:
          summary: "The beacon client is not synced."

      - alert: ClientSyncStatusExecution
        expr: rocketpool_node_sync_progress{client="execution"} < 1.0
        labels:
          severity: critical
        annotations:
          summary: "The execution client is not synced."

      - alert: UpcomingSyncCommittee
        expr: rocketpool_beacon_upcoming_sync_committee > 0
        labels:
          severity: warning
          job: validator
        annotations:
          summary: "Your Rocket Pool node is about to become part of a sync committee."
          description: |
            If you were planning on doing maintenance to your node, **you should wait until the sync committee is over**. Not only are they worth an **extremely** large amount of ETH, but if you miss attestations during a sync committee, you **lose an extremely large amount of ETH** instead!
            You should be online as long as possible while you are in a sync committee.

      - alert: ActiveSyncCommittee
        expr: rocketpool_beacon_active_sync_committee > 0
        labels:
          severity: warning
          job: validator
        annotations:
          summary: "Your Rocket Pool node is part of a sync committee."
          description: |
            If you were planning on doing maintenance to your node, **you should wait until the sync committee is over**. Not only are they worth an **extremely** large amount of ETH, but if you miss attestations during a sync committee, you **lose an extremely large amount of ETH** instead!
            You should be online as long as possible while you are in a sync committee.

      - alert: UpcomingProposal
        expr: rocketpool_beacon_upcoming_proposals > 0
        labels:
          severity: warning
          job: validator
        annotations:
          summary: "Your Rocket Pool node is about to propose a block."
          description: |
            You have {{ $value }} block proposals coming up in the next few minutes. If you were planning on taking your node down for maintenance, you should wait until after the proposals because they're worth a lot of ETH!

      - alert: LowDiskSpaceWarning
        expr: node_filesystem_avail_bytes{job="node", mountpoint="/"} / 1024^3 < 200
        labels:
          severity: warning
          job: node
        annotations:
          summary: "Device {{ $labels.device }} on instance {{ $labels.instance }} is getting low on disk space."
          description: "{{ $labels.instance }} has low disk space. Currently has {{ humanize $value }} free."

      - alert: LowDiskSpaceCritical
        # NOTE: 50GB taken from PruneFreeSpaceRequired in rocketpool-cli's nethermind pruning (it won't prune below 50GB)
        expr: node_filesystem_avail_bytes{job="node", mountpoint="/"} / 1024^3 < 50
        labels:
          severity: critical
          job: node
        annotations:
          summary: "Device {{ $labels.device }} on instance {{ $labels.instance }} has critically low disk space."
          description: "{{ $labels.instance }} has critically low disk space. Currently has {{ humanize $value }} free."

      - alert: OSUpdatesAvailable
        expr: max(os_upgrades_pending{job="node"}) > 0
        labels:
          severity: warning
          job: node
        annotations:
          summary: "Rocket Pool OS Updates Available."
          description: |
            There are updates available for your OS that haven't been applied yet. You should update your OS.
            For more information on updating see the documentation at https://docs.rocketpool.net/guides/node/updates#updating-your-operating-system

      - alert: RPUpdatesAvailable
        expr: max(os_upgrades_pending{job="node"}) > 0
        labels:
          severity: warning
          job: node
        annotations:
          summary: "Rocket Pool Smartnode Update Available."
          description: |
            There are updates available for the Rocket Pool Smartnode that haven't been applied yet. You should update the smartnode stack.
            For more information on updating see the documentation at https://docs.rocketpool.net/guides/node/updates#updating-the-smartnode-stack
